/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as settingsRouteRouteImport } from './routes/(settings)/route'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as mainIndexRouteImport } from './routes/(main)/index'
import { Route as mainAuthorizeUserRouteImport } from './routes/(main)/authorize/user'
import { Route as mainAuthorizeRoleRouteImport } from './routes/(main)/authorize/role'
import { Route as mainAuthorizePermissionRouteImport } from './routes/(main)/authorize/permission'
import { Route as mainAiModelsRouteImport } from './routes/(main)/ai/models'
import { Route as mainAiManageProvidersRouteImport } from './routes/(main)/ai/manage-providers'
import { Route as mainAiManageModelsRouteImport } from './routes/(main)/ai/manage-models'
import { Route as mainAiConfigurationRouteImport } from './routes/(main)/ai/configuration'
import { Route as mainAiAnalyticsRouteImport } from './routes/(main)/ai/analytics'
import { Route as mainShipWorkflowsIndexRouteImport } from './routes/(main)/ship/workflows/index'
import { Route as mainShipStaticAndServerlessIndexRouteImport } from './routes/(main)/ship/static-and-serverless/index'
import { Route as mainShipObservabilityIndexRouteImport } from './routes/(main)/ship/observability/index'

const settingsRouteRoute = settingsRouteRouteImport.update({
  id: '/(settings)',
  getParentRoute: () => rootRouteImport,
} as any)
const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const mainIndexRoute = mainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainAuthorizeUserRoute = mainAuthorizeUserRouteImport.update({
  id: '/authorize/user',
  path: '/authorize/user',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainAuthorizeRoleRoute = mainAuthorizeRoleRouteImport.update({
  id: '/authorize/role',
  path: '/authorize/role',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainAuthorizePermissionRoute = mainAuthorizePermissionRouteImport.update({
  id: '/authorize/permission',
  path: '/authorize/permission',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainAiModelsRoute = mainAiModelsRouteImport.update({
  id: '/ai/models',
  path: '/ai/models',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainAiManageProvidersRoute = mainAiManageProvidersRouteImport.update({
  id: '/ai/manage-providers',
  path: '/ai/manage-providers',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainAiManageModelsRoute = mainAiManageModelsRouteImport.update({
  id: '/ai/manage-models',
  path: '/ai/manage-models',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainAiConfigurationRoute = mainAiConfigurationRouteImport.update({
  id: '/ai/configuration',
  path: '/ai/configuration',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainAiAnalyticsRoute = mainAiAnalyticsRouteImport.update({
  id: '/ai/analytics',
  path: '/ai/analytics',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainShipWorkflowsIndexRoute = mainShipWorkflowsIndexRouteImport.update({
  id: '/ship/workflows/',
  path: '/ship/workflows/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainShipStaticAndServerlessIndexRoute =
  mainShipStaticAndServerlessIndexRouteImport.update({
    id: '/ship/static-and-serverless/',
    path: '/ship/static-and-serverless/',
    getParentRoute: () => mainRouteRoute,
  } as any)
const mainShipObservabilityIndexRoute =
  mainShipObservabilityIndexRouteImport.update({
    id: '/ship/observability/',
    path: '/ship/observability/',
    getParentRoute: () => mainRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof mainIndexRoute
  '/ai/analytics': typeof mainAiAnalyticsRoute
  '/ai/configuration': typeof mainAiConfigurationRoute
  '/ai/manage-models': typeof mainAiManageModelsRoute
  '/ai/manage-providers': typeof mainAiManageProvidersRoute
  '/ai/models': typeof mainAiModelsRoute
  '/authorize/permission': typeof mainAuthorizePermissionRoute
  '/authorize/role': typeof mainAuthorizeRoleRoute
  '/authorize/user': typeof mainAuthorizeUserRoute
  '/ship/observability': typeof mainShipObservabilityIndexRoute
  '/ship/static-and-serverless': typeof mainShipStaticAndServerlessIndexRoute
  '/ship/workflows': typeof mainShipWorkflowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof mainIndexRoute
  '/ai/analytics': typeof mainAiAnalyticsRoute
  '/ai/configuration': typeof mainAiConfigurationRoute
  '/ai/manage-models': typeof mainAiManageModelsRoute
  '/ai/manage-providers': typeof mainAiManageProvidersRoute
  '/ai/models': typeof mainAiModelsRoute
  '/authorize/permission': typeof mainAuthorizePermissionRoute
  '/authorize/role': typeof mainAuthorizeRoleRoute
  '/authorize/user': typeof mainAuthorizeUserRoute
  '/ship/observability': typeof mainShipObservabilityIndexRoute
  '/ship/static-and-serverless': typeof mainShipStaticAndServerlessIndexRoute
  '/ship/workflows': typeof mainShipWorkflowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(main)': typeof mainRouteRouteWithChildren
  '/(settings)': typeof settingsRouteRoute
  '/(main)/': typeof mainIndexRoute
  '/(main)/ai/analytics': typeof mainAiAnalyticsRoute
  '/(main)/ai/configuration': typeof mainAiConfigurationRoute
  '/(main)/ai/manage-models': typeof mainAiManageModelsRoute
  '/(main)/ai/manage-providers': typeof mainAiManageProvidersRoute
  '/(main)/ai/models': typeof mainAiModelsRoute
  '/(main)/authorize/permission': typeof mainAuthorizePermissionRoute
  '/(main)/authorize/role': typeof mainAuthorizeRoleRoute
  '/(main)/authorize/user': typeof mainAuthorizeUserRoute
  '/(main)/ship/observability/': typeof mainShipObservabilityIndexRoute
  '/(main)/ship/static-and-serverless/': typeof mainShipStaticAndServerlessIndexRoute
  '/(main)/ship/workflows/': typeof mainShipWorkflowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai/analytics'
    | '/ai/configuration'
    | '/ai/manage-models'
    | '/ai/manage-providers'
    | '/ai/models'
    | '/authorize/permission'
    | '/authorize/role'
    | '/authorize/user'
    | '/ship/observability'
    | '/ship/static-and-serverless'
    | '/ship/workflows'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai/analytics'
    | '/ai/configuration'
    | '/ai/manage-models'
    | '/ai/manage-providers'
    | '/ai/models'
    | '/authorize/permission'
    | '/authorize/role'
    | '/authorize/user'
    | '/ship/observability'
    | '/ship/static-and-serverless'
    | '/ship/workflows'
  id:
    | '__root__'
    | '/(main)'
    | '/(settings)'
    | '/(main)/'
    | '/(main)/ai/analytics'
    | '/(main)/ai/configuration'
    | '/(main)/ai/manage-models'
    | '/(main)/ai/manage-providers'
    | '/(main)/ai/models'
    | '/(main)/authorize/permission'
    | '/(main)/authorize/role'
    | '/(main)/authorize/user'
    | '/(main)/ship/observability/'
    | '/(main)/ship/static-and-serverless/'
    | '/(main)/ship/workflows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainRouteRoute: typeof mainRouteRouteWithChildren
  settingsRouteRoute: typeof settingsRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(settings)': {
      id: '/(settings)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof settingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/': {
      id: '/(main)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/authorize/user': {
      id: '/(main)/authorize/user'
      path: '/authorize/user'
      fullPath: '/authorize/user'
      preLoaderRoute: typeof mainAuthorizeUserRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/authorize/role': {
      id: '/(main)/authorize/role'
      path: '/authorize/role'
      fullPath: '/authorize/role'
      preLoaderRoute: typeof mainAuthorizeRoleRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/authorize/permission': {
      id: '/(main)/authorize/permission'
      path: '/authorize/permission'
      fullPath: '/authorize/permission'
      preLoaderRoute: typeof mainAuthorizePermissionRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/ai/models': {
      id: '/(main)/ai/models'
      path: '/ai/models'
      fullPath: '/ai/models'
      preLoaderRoute: typeof mainAiModelsRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/ai/manage-providers': {
      id: '/(main)/ai/manage-providers'
      path: '/ai/manage-providers'
      fullPath: '/ai/manage-providers'
      preLoaderRoute: typeof mainAiManageProvidersRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/ai/manage-models': {
      id: '/(main)/ai/manage-models'
      path: '/ai/manage-models'
      fullPath: '/ai/manage-models'
      preLoaderRoute: typeof mainAiManageModelsRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/ai/configuration': {
      id: '/(main)/ai/configuration'
      path: '/ai/configuration'
      fullPath: '/ai/configuration'
      preLoaderRoute: typeof mainAiConfigurationRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/ai/analytics': {
      id: '/(main)/ai/analytics'
      path: '/ai/analytics'
      fullPath: '/ai/analytics'
      preLoaderRoute: typeof mainAiAnalyticsRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/ship/workflows/': {
      id: '/(main)/ship/workflows/'
      path: '/ship/workflows'
      fullPath: '/ship/workflows'
      preLoaderRoute: typeof mainShipWorkflowsIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/ship/static-and-serverless/': {
      id: '/(main)/ship/static-and-serverless/'
      path: '/ship/static-and-serverless'
      fullPath: '/ship/static-and-serverless'
      preLoaderRoute: typeof mainShipStaticAndServerlessIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/ship/observability/': {
      id: '/(main)/ship/observability/'
      path: '/ship/observability'
      fullPath: '/ship/observability'
      preLoaderRoute: typeof mainShipObservabilityIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
  }
}

interface mainRouteRouteChildren {
  mainIndexRoute: typeof mainIndexRoute
  mainAiAnalyticsRoute: typeof mainAiAnalyticsRoute
  mainAiConfigurationRoute: typeof mainAiConfigurationRoute
  mainAiManageModelsRoute: typeof mainAiManageModelsRoute
  mainAiManageProvidersRoute: typeof mainAiManageProvidersRoute
  mainAiModelsRoute: typeof mainAiModelsRoute
  mainAuthorizePermissionRoute: typeof mainAuthorizePermissionRoute
  mainAuthorizeRoleRoute: typeof mainAuthorizeRoleRoute
  mainAuthorizeUserRoute: typeof mainAuthorizeUserRoute
  mainShipObservabilityIndexRoute: typeof mainShipObservabilityIndexRoute
  mainShipStaticAndServerlessIndexRoute: typeof mainShipStaticAndServerlessIndexRoute
  mainShipWorkflowsIndexRoute: typeof mainShipWorkflowsIndexRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainIndexRoute: mainIndexRoute,
  mainAiAnalyticsRoute: mainAiAnalyticsRoute,
  mainAiConfigurationRoute: mainAiConfigurationRoute,
  mainAiManageModelsRoute: mainAiManageModelsRoute,
  mainAiManageProvidersRoute: mainAiManageProvidersRoute,
  mainAiModelsRoute: mainAiModelsRoute,
  mainAuthorizePermissionRoute: mainAuthorizePermissionRoute,
  mainAuthorizeRoleRoute: mainAuthorizeRoleRoute,
  mainAuthorizeUserRoute: mainAuthorizeUserRoute,
  mainShipObservabilityIndexRoute: mainShipObservabilityIndexRoute,
  mainShipStaticAndServerlessIndexRoute: mainShipStaticAndServerlessIndexRoute,
  mainShipWorkflowsIndexRoute: mainShipWorkflowsIndexRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  mainRouteRoute: mainRouteRouteWithChildren,
  settingsRouteRoute: settingsRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
